sudo: required
servies:
  - docker

before_install:
  - docker build -t ivalexig/react-tests -f ./client/Dockerfile.dev ./client

# Can add other tests here (eg. back end server tests)
script:
  - docker run -e CI=true ivalexig/react-tests npm test

after_success:
  - docker build -t ivalexig/multi-client ./client
  - docler build -t ivalexig/multi-nginx ./nginx
  - docler build -t ivalexig/multi-server ./server
  - docler build -t ivalexig/multi-worker ./worker
  # Log in to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push all images to docker hub
  - docker push ivalexig/multi-client
  - docker push ivalexig/multi-nginx
  - docker push ivalexig/multi-server
  - docker push ivalexig/multi-worker

# Push project to AWS beanstalk
deploy:
  provider: elastocbeanstalk
  region: 'ap-southeast-2'
  app: 'Multi-Docker'
  env: 'Multidocker-env'
  bucket_name: 'elasticbeanstalk-ap-southeast-2-989835879183'
  bucket_path: 'docker-multi'
  on:
    branch: main
access_key_id: $AWS_ACCESS_KEY
secret_access_key: $AWS_SECRET_KEY
