sudo: required
servies:
  - docker

before_install:
  - docker build -t ivalexig/react-test -f ./client/Dockerfile.dev ./client

# Can add other tests here (eg. back end server tests)
script:
  - docker run ivalexig/react-tests npm test -- --coverage

after_success:
  - docker build -t ivalexig/multi-client ./client
  - docler build -t ivalexig/multi-nginx ./nginx
  - docler build -t ivalexig/multi-server ./server
  - docler build -t ivalexig/multi-worker ./worker
  # Log in to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push all images to docker hub
  - docker push ivalexig/multi-client
  - docker push ivalexig/multi-nginx
  - docker push ivalexig/multi-server
  - docker push ivalexig/multi-worker
